### PR TITLE
Updated progname for proxy

### PR DESCRIPTION
**Pull request by lzap**
Couple of changes @swadeley 

* Let's use generic 0.0.0.0 instead of giving it IP addresses.
* Package `foreman-proxy-journald` was actually missing in instructions, therefore proxy was not logging via systemd-journald but via STDOUT-journald without any structured fields.
* Fixed proxy transformations in the main configuration.
* Small remarks here and there.

### CODE REVIEW

**Review by swadeley — CHANGES_REQUESTED** [review]
Hello

s/configure either external/configure either an external/
s/Kibana expect ElasticSearch/Kibana expects ElasticSearch/

thank you

**Comment by lzap** [comment]
Will do, one thing tho - Candlepin does not appear to set foremn.request UUID, can you confirm?

**Comment by swadeley** [comment]
Hello @lzap , I created a new org "Test". I uploaded a manifest. In the Kibana filter field (search box) I entered "manifest" and found the event:

message:
    Importing new rules from manifest, current version: 5.36 new version: 5.36
foreman.request:
    c8c3484a-4cc8-4e9b-b806-712c9afdffc1
@timestamp:
    June 10th 2019, 10:31:42.646
level:
    info
foreman.app:
    candlepin
foreman.logger:
    org.candlepin.sync.RulesImporter
foreman.org_name:
    test
foreman.org_label:
    test
_id:
    AWtAuqdbUcseTGY_48Vf
_type:
    events
_index:
    project.foreman-logs.2019.06.10
_score:
    -

**Comment by lzap** [comment]
Thank you, I think we are done this is the final version for Foreman 1.22.

**Pull request merged**
